In [2]:
%matplotlib qt
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

In [3]:
ds = pd.read_csv("raw_data_activity/activity_drill_01.txt", sep=',')
df = ds
df

,1686748815.1614938,b'Port,2,1.000000,1.000000.1,1.000000.2,1.000000.3,1.000000.4,1.000000.5,1.000000.6,...,262.207800,-2.043300,105.046800,1.739700,78.425600,1.210500,22.858300,-3.634500,33.916800,-3.139600'
0,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,365.0681,-1.9736,100.1672,1.8883,78.5011,1.2141,23.0991,-3.6364,36.4795,-2.746900'
1,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,344.6341,-1.9815,99.4633,1.9675,81.4954,1.2313,23.3182,-3.6262,34.8435,-3.111700'
2,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,303.3749,-1.9601,97.4103,1.9908,74.4046,1.2267,22.9273,-3.6252,35.1152,-3.093300'
3,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,339.1493,-1.9886,99.1331,1.9530,77.9769,1.2180,19.2638,-3.8045,33.8944,-3.111400'
4,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,459.0769,-1.8458,96.8225,1.9192,75.8129,1.2333,23.1666,-3.6102,34.6477,-3.120300'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,310.6368,-1.2777,72.5444,2.6322,44.1057,1.4378,27.0286,-3.5628,43.3005,-2.525500'
194,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,300.1551,-1.6201,73.5743,2.6595,42.5603,1.4403,26.4971,-3.5726,42.6118,-2.525700'
195,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,379.0613,-1.5850,67.2811,2.6868,48.3179,1.4105,27.2639,-3.5746,42.8405,-2.995600'
196,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,267.5186,-1.3996,68.9093,2.7169,48.9424,1.4259,27.2646,-3.5856,43.3295,-2.560400'
197,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,297.5096,-1.2063,68.5289,2.7536,48.5848,1.4127,26.8791,-3.5803,41.8681,-3.074500'

In [4]:
df.columns.values[0] = "timestamp"  
df.rename(columns={'1':'Port1'}, inplace=True)
df.rename(columns={'2':'Port2'}, inplace=True)
df.rename(columns={'3':'Port3'}, inplace=True)
df.rename(columns={'4':'Port4'}, inplace=True)
df.columns

Index(['timestamp', 'b'Port', 'Port2', '1.000000', '1.000000.1', '1.000000.2',
       '1.000000.3', '1.000000.4', '1.000000.5', '1.000000.6', '1.000000.7',
       '1.000000.8', '1.000000.9', '1.000000.10', '1.000000'', 'b'Port.1',
       'Port3', '0.000000', '0.000000.1', '0.000000.2', '0.000000.3',
       '0.000000.4', '0.000000.5', '0.000000.6', '0.000000.7', '0.000000.8',
       '0.000000.9', '0.000000.10', '0.000000'', 'b'Port.2', 'Port4',
       '176.844600', '-1.893900', '75.473500', '1.889600', '43.253300',
       '-0.846500', '138.057800', '-0.543000', '64.800200', '-0.919600',
       '65.726000', '-1.202600'', 'b'Port.3', 'Port1', '104.172600',
       '-1.107200', '262.207800', '-2.043300', '105.046800', '1.739700',
       '78.425600', '1.210500', '22.858300', '-3.634500', '33.916800',
       '-3.139600''],
      dtype='object')

In [5]:
# rename all columns
port_mappings = {
    'Port1': {'prefix': 'R1_', 'range': 12},
    'Port2': {'prefix': 'R2_', 'range': 12},
    'Port3': {'prefix': 'R3_', 'range': 12},
    'Port4': {'prefix': 'R4_', 'range': 12}
}
print(port_mappings)
for port, mapping in port_mappings.items():
    start_column = port
    prefix = mapping['prefix']
    column_range = mapping['range']

    if start_column in df.columns:
        start_index = df.columns.get_loc(start_column)
        new_column_names = [prefix + str(i) for i in range(1, column_range + 1)]
        df = df.rename(columns=dict(zip(df.columns[start_index + 1:start_index + column_range + 1], new_column_names)))
    else:
        print(f"Error: column'{start_column}' not found")

df.columns

{'Port1': {'prefix': 'R1_', 'range': 12}, 'Port2': {'prefix': 'R2_', 'range': 12}, 'Port3': {'prefix': 'R3_', 'range': 12}, 'Port4': {'prefix': 'R4_', 'range': 12}}

Index(['timestamp', 'b'Port', 'Port2', 'R2_1', 'R2_2', 'R2_3', 'R2_4', 'R2_5',
       'R2_6', 'R2_7', 'R2_8', 'R2_9', 'R2_10', 'R2_11', 'R2_12', 'b'Port.1',
       'Port3', 'R3_1', 'R3_2', 'R3_3', 'R3_4', 'R3_5', 'R3_6', 'R3_7', 'R3_8',
       'R3_9', 'R3_10', 'R3_11', 'R3_12', 'b'Port.2', 'Port4', 'R4_1', 'R4_2',
       'R4_3', 'R4_4', 'R4_5', 'R4_6', 'R4_7', 'R4_8', 'R4_9', 'R4_10',
       'R4_11', 'R4_12', 'b'Port.3', 'Port1', 'R1_1', 'R1_2', 'R1_3', 'R1_4',
       'R1_5', 'R1_6', 'R1_7', 'R1_8', 'R1_9', 'R1_10', 'R1_11', 'R1_12'],
      dtype='object')

In [7]:
df

,timestamp,b'Port,Port2,R2_1,R2_2,R2_3,R2_4,R2_5,R2_6,R2_7,...,R1_3,R1_4,R1_5,R1_6,R1_7,R1_8,R1_9,R1_10,R1_11,R1_12
0,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,365.0681,-1.9736,100.1672,1.8883,78.5011,1.2141,23.0991,-3.6364,36.4795,-2.746900'
1,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,344.6341,-1.9815,99.4633,1.9675,81.4954,1.2313,23.3182,-3.6262,34.8435,-3.111700'
2,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,303.3749,-1.9601,97.4103,1.9908,74.4046,1.2267,22.9273,-3.6252,35.1152,-3.093300'
3,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,339.1493,-1.9886,99.1331,1.9530,77.9769,1.2180,19.2638,-3.8045,33.8944,-3.111400'
4,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,459.0769,-1.8458,96.8225,1.9192,75.8129,1.2333,23.1666,-3.6102,34.6477,-3.120300'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,310.6368,-1.2777,72.5444,2.6322,44.1057,1.4378,27.0286,-3.5628,43.3005,-2.525500'
194,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,300.1551,-1.6201,73.5743,2.6595,42.5603,1.4403,26.4971,-3.5726,42.6118,-2.525700'
195,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,379.0613,-1.5850,67.2811,2.6868,48.3179,1.4105,27.2639,-3.5746,42.8405,-2.995600'
196,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,267.5186,-1.3996,68.9093,2.7169,48.9424,1.4259,27.2646,-3.5856,43.3295,-2.560400'
197,1.686749e+09,b'Port,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,297.5096,-1.2063,68.5289,2.7536,48.5848,1.4127,26.8791,-3.5803,41.8681,-3.074500'

In [ ]:
# df.dtypes

In [6]:
def reciprocal(d):
    # drop timestamp and identify numeric columns
    ds=d.drop(['timestamp',"b'Port","b'Port.1","b'Port.2", "b'Port.3",'Port1','Port2', 'Port3', 'Port4'], axis=1)
    numeric_columns = ds.select_dtypes(include=[np.number]).columns
    ds[numeric_columns] = ds[numeric_columns].apply(lambda x: 1 / x)
    return ds

dd = reciprocal(df)
dd

,R2_1,R2_2,R2_3,R2_4,R2_5,R2_6,R2_7,R2_8,R2_9,R2_10,...,R1_3,R1_4,R1_5,R1_6,R1_7,R1_8,R1_9,R1_10,R1_11,R1_12
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.002739,-0.506688,0.009983,0.529577,0.012739,0.823655,0.043292,-0.274997,0.027413,-2.746900'
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.002902,-0.504668,0.010054,0.508259,0.012271,0.812150,0.042885,-0.275771,0.028700,-3.111700'
2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.003296,-0.510178,0.010266,0.502311,0.013440,0.815195,0.043616,-0.275847,0.028478,-3.093300'
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.002949,-0.502866,0.010087,0.512033,0.012824,0.821018,0.051911,-0.262847,0.029503,-3.111400'
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.002178,-0.541771,0.010328,0.521050,0.013190,0.810833,0.043166,-0.276993,0.028862,-3.120300'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.003219,-0.782656,0.013785,0.379910,0.022673,0.695507,0.036998,-0.280678,0.023094,-2.525500'
194,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.003332,-0.617246,0.013592,0.376011,0.023496,0.694300,0.037740,-0.279908,0.023468,-2.525700'
195,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.002638,-0.630915,0.014863,0.372190,0.020696,0.708968,0.036679,-0.279752,0.023342,-2.995600'
196,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.003738,-0.714490,0.014512,0.368067,0.020432,0.701311,0.036678,-0.278893,0.023079,-2.560400'
197,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.003361,-0.828981,0.014592,0.363161,0.020583,0.707864,0.037204,-0.279306,0.023885,-3.074500'

In [6]:
dd.to_csv('raw_data_activity/activity_painting_01.csv', index=False)

In [8]:
dd = pd.read_csv('raw_data_activity/activity_lifting_01.csv')

In [15]:

plt.title('Activity: Lifting(Left arm)', fontsize=22, fontweight='bold')
plt.xlabel('Data points', fontsize=18, fontweight='bold')
plt.ylabel('Amplitude(um)', fontsize=18, fontweight='bold')
plt.grid(True)
plt.legend(['R1_1'])

# Set the text size of the tick labels on both axes
plt.tick_params(axis='both', labelsize=18)
plt.plot(dd.index, dd[['R1_1', 'R1_3','R1_5','R1_7','R1_9','R1_11']])

[<matplotlib.lines.Line2D at 0x2933bf9fe08>,
 <matplotlib.lines.Line2D at 0x2933c12e3c8>,
 <matplotlib.lines.Line2D at 0x2933bfa5408>,
 <matplotlib.lines.Line2D at 0x2933c12ee48>,
 <matplotlib.lines.Line2D at 0x2933bf9f608>,
 <matplotlib.lines.Line2D at 0x2933be27108>]

In [12]:
plt.title('Activity: Painting(...)', fontsize=22, fontweight='bold')
plt.xlabel('Data points', fontsize=18, fontweight='bold')
plt.ylabel('Amplitude(um)', fontsize=18, fontweight='bold')
plt.grid(True)
plt.legend(['R2_1', 'R2_3', 'R2_5', 'R2_7', 'R2_9', 'R2_11'])

# Set the text size of the tick labels on both axes
plt.tick_params(axis='both', labelsize=18)
plt.plot(dd.index, dd[['R2_1', 'R2_3', 'R2_5', 'R2_7', 'R2_9', 'R2_11']])

[<matplotlib.lines.Line2D at 0x29339108d08>,
 <matplotlib.lines.Line2D at 0x29339129148>,
 <matplotlib.lines.Line2D at 0x2933913a588>,
 <matplotlib.lines.Line2D at 0x2933913a788>,
 <matplotlib.lines.Line2D at 0x2933913a9c8>,
 <matplotlib.lines.Line2D at 0x2933913ac08>]

In [11]:

plt.legend(['R3_1', 'R3_3', 'R3_5', 'R3_7', 'R3_9', 'R3_11'])
plt.plot(dd.index, dd[['R3_1', 'R3_3', 'R3_5', 'R3_7', 'R3_9', 'R3_11']])

[<matplotlib.lines.Line2D at 0x2933909ac08>,
 <matplotlib.lines.Line2D at 0x2933909a448>,
 <matplotlib.lines.Line2D at 0x293390ada08>,
 <matplotlib.lines.Line2D at 0x293390adc08>,
 <matplotlib.lines.Line2D at 0x293390ade48>,
 <matplotlib.lines.Line2D at 0x293390b30c8>]

In [14]:
plt.legend(['R4_1', 'R4_3', 'R4_5', 'R4_7', 'R4_9', 'R4_11'])
plt.title('Activity: Lifting(Right arm)', fontsize=22, fontweight='bold')
plt.xlabel('Data points', fontsize=18, fontweight='bold')
plt.ylabel('Amplitude(um)', fontsize=18, fontweight='bold')
plt.grid(True)

# Set the text size of the tick labels on both axes
plt.tick_params(axis='both', labelsize=18)
plt.plot(dd.index, dd[['R4_1', 'R4_3', 'R4_5', 'R4_7', 'R4_9','R4_11']])

[<matplotlib.lines.Line2D at 0x2933bf9fac8>,
 <matplotlib.lines.Line2D at 0x2933bf95448>,
 <matplotlib.lines.Line2D at 0x2933bfa5048>,
 <matplotlib.lines.Line2D at 0x2933bfa5208>,
 <matplotlib.lines.Line2D at 0x2933bfa5448>,
 <matplotlib.lines.Line2D at 0x2933bfa5688>]